### ISSUE TITLE
Not Extracting? Values changed maybe...

### ISSUE THREAD

**Issue by Solarkoid** [Pupix/lol-wad-parser#20] opened 2017-11-14 19:38 UTC
So I have this 1 GB file of Wad... and It extracted 10 pics
thats it... Try checking everything... I think values changed. :100:

**Comment by Pupix** [comment] 2017-11-14 22:19
what? Is there an error or something? what file are you trying to extract?

I can't help you just saying: *stuff doesn't work, fix it!*

**Comment by Solarkoid** [comment] 2017-11-15 16:08
So Im trying to extract default-assets.wad It is 1 GBs and it is strange I have normal code (Renamed file cause of reasons).

![](https://i.snag.gy/F90DUR.jpg)

`var WadParser = require('lol-wad-parser'),
    wad = new WadParser();

wad.extract('assets.wad', 'unpacked_stuff_3', function (error) {
    console.log(data);
});
`
I didnt say I to fix it, it is just odd that last patches assets just extracted on huge amounts but this one was just 10 or so pictures?

**Comment by Pupix** [comment] 2017-11-16 10:01
what is the error you are getting? you are doing `console.log(data);` instead of `console.log(error)`.

**Comment by Solarkoid** [comment] 2017-11-17 16:07
I am not getting any errors... It just starts and finishes only extracting those materials... Tried 3 times already.

**Comment by Pupix** [comment] 2017-11-21 22:32
Can't reproduce this.
![](https://i.imgur.com/6G686mi.png)

Your file must be corrupt or you must be doing something other than what you showed here. Either way I am closing this until further details come to light.

**Closed as completed by Pupix** 2017-11-21 22:32 UTC

**Comment by Pupix** [comment] 2017-11-25 14:04
@Solarkoid What you may have experienced was the new compression with `zstandard`. However there was a error thrown in that case so you should have been at least getting that.

The library has been updated to support that, so you may be able to get it working now.
